### ISSUE TITLE
"Next steps" remains the same for all the pages under Deliverables 

### ISSUE THREAD

**Issue by indcoder** [MicrosoftDocs/well-architected#134]
Every page under Deliverable has "Architect's Checklist" as the Next Step instead of the subsequent page under Deliverable.

eg: 
1.
<img width="711" alt="image" src="https://github.com/MicrosoftDocs/well-architected/assets/2099300/856c71cc-ed8e-4fd2-98ba-aa4c4c520ab3">

2.
<img width="482" alt="image" src="https://github.com/MicrosoftDocs/well-architected/assets/2099300/6f7997a9-1433-4bf5-9dcc-6250465ce9e8">

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62c9f3c3-6145-aade-9aef-530b0003e31f
* Version Independent ID: 62c9f3c3-6145-aade-9aef-530b0003e31f
* Content: [Solution architect's checklist - Microsoft Azure Well-Architected Framework](https://learn.microsoft.com/en-us/azure/well-architected/architect-role/checklist)
* Content Source: [well-architected/architect-role/checklist.md](https://github.com/MicrosoftDocs/well-architected/blob/main/well-architected/architect-role/checklist.md)
* Service: **waf**
* GitHub Login: @ckittel
* Microsoft Alias: **chkittel**

**Comment by PageWriter-MSFT** [comment]
Hello @indcoder, the information layout is by design. 

The Architect's guides surface common skills needed by the job function. All guides are tied to the Architect's checklist to allow the reader to choose their area of interest instead of a suggested sequential flow. 

Thanks for the feedback and checking out the refreshed WAF.
